[project]
name = "sample-rag-ui"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "langchain-core>=0.3.76",
    "requests>=2.32.5",
    "streamlit>=1.49.1",
]
